---
'ALTERNATE_DRIVING_DIRECTION': 'False'
'AWS_REGION': 'us-east-1'
'BEST_MODEL_METRIC': 'progress'
'BODY_SHELL_TYPE': 'deepracer'
'CAMERA_MAIN_ENABLE': 'True'
'CAMERA_SUB_ENABLE': 'True'
'CAR_COLOR': 'Red'
'CAR_NAME': 'FastCar'
'CHANGE_START_POSITION': 'True'
'DISPLAY_NAME': 'FastCar'
'ENABLE_DOMAIN_RANDOMIZATION': 'False'
'JOB_TYPE': 'TRAINING'
'KINESIS_VIDEO_STREAM_NAME': ''
'METRICS_S3_BUCKET': 'deepracer-bucket-4212'
'METRICS_S3_OBJECT_KEY': 'Dist-exp-neg10-2Hours/metrics/TrainingMetrics.json'
'MIN_EVAL_TRIALS': '5'
'MODEL_METADATA_FILE_S3_KEY': 'custom_files/model_metadata.json'
'NUM_WORKERS': '1'
'RACER_NAME': 'FastCar'
'RACE_TYPE': 'TIME_TRIAL'
'REVERSE_DIR': !!bool 'false'
'REWARD_FILE_S3_KEY': 'custom_files/reward_function.py'
'ROBOMAKER_SIMULATION_JOB_ACCOUNT_ID': 'Dummy'
'ROUND_ROBIN_ADVANCE_DIST': '0.05'
'SAGEMAKER_SHARED_S3_BUCKET': 'deepracer-bucket-4212'
'SAGEMAKER_SHARED_S3_PREFIX': 'Dist-exp-neg10-2Hours'
'SIMTRACE_S3_BUCKET': 'deepracer-bucket-4212'
'SIMTRACE_S3_PREFIX': 'Dist-exp-neg10-2Hours'
'START_POSITION_OFFSET': '0.0'
'TRAINING_JOB_ARN': 'arn:Dummy'
'WORLD_NAME': 'thunder_hill_pro_cw'
